In [5]:
import numpy as np
l=[10,30,25,43,21]
arr=np.array(l)
print(arr)

[10 30 25 43 21]


In [11]:
import numpy as np
a=np.array(42)
b=np.array([1,2,2,3,4])
c= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
d=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])



print("a array",a)
print("b array",b)
print("c array",c)
print("d array",d)

print("a array dime",a.ndim)
print("b array dime",b.ndim)
print("c array dime",c.ndim)
print("d array dime",d.ndim)


a array 42
b array [1 2 2 3 4]
c array [[1 2 3]
 [4 5 6]
 [7 8 9]]
d array [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
a array dime 0
b array dime 1
c array dime 2
d array dime 3


In [18]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
sarr=arr[1:5]
print(arr)
print(sarr)
sarr[2]=100
print(sarr)
print(arr)

[1 2 3 4 5 6 7]
[2 3 4 5]
[  2   3 100   5]
[  1   2   3 100   5   6   7]


In [20]:
#1. 1D array-vector
#2. 2D array-matrix
#3. 3D array-tensor

In [22]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [23]:
#The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

#The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [24]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [29]:
import numpy as np
a=np.zeros((6,2))
print(a)



[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [30]:
#numpy.zeros() in Python
#The numpy.zeros() function is one of the most significant functions which is used in machine learning programs widely. This function is used to  generate an array containing zeros.
#The numpy.zeros() function provide a new array of given shape and type, which is filled with zeros.

In [32]:
#numpy.zeros() without order
import numpy as np
a=np.zeros((6,),dtype=int)
print(a)

[0 0 0 0 0 0]


In [ ]:

#The NumPy ones() function in Python is used to create an array of the specified shape and type, where all the elements are set to 1. This function is very similar to zeros(). The ones () function takes three arguments and returns the array filled with value 1. In this article, I will explain how to use the NumPy ones() function with examples.

In [33]:
import numpy as np
a=np.ones((6,2))
print(a)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [35]:
import numpy as np
a=np.ones((6,2)) * 10
print(a)


[[10. 10.]
 [10. 10.]
 [10. 10.]
 [10. 10.]
 [10. 10.]
 [10. 10.]]


In [37]:
import numpy as np
a=np.ones(5,dtype=int)
print(a)


[1 1 1 1 1]


In [38]:
import numpy as np
a=np.ones((6),dtype=int)
print(a)

[1 1 1 1 1 1]


In [39]:
import numpy as np
a=np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [43]:

#The eye tool returns a 2-D array with 1's as the diagonal and 0's elsewhere. The diagonal can be main, upper, or lower depending on the optional parameter k. A positive k is for the upper diagonal, a negative k is for the lower, and a Øk (default) is for the main diagonal.

In [42]:
import numpy as np
arr4=np.eye(7)
print(arr4)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
#DIAGONAL

In [45]:
import numpy as np
arr=np.diag((3,4,1,6))
print(arr)
print(arr.ndim)
print(arr.shape)

[[3 0 0 0]
 [0 4 0 0]
 [0 0 1 0]
 [0 0 0 6]]
2
(4, 4)


In [ ]:
#25 july 2024

In [3]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[1,3,6]])
print(np.diag(arr))
print(np.diag((3,9,5)))

[1 5 6]
[[3 0 0]
 [0 9 0]
 [0 0 5]]


In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [5]:
#randint() is an inbuilt function of the randon module in Python3. The random module gives access to various useful functions one of them being able to generate random numbers, which is randint()

#This function generates an array of specified shape and fills it with random samples from a unifors distribution over the interval [0, 1).



In [6]:
import numpy as np
rand=np.random.rand(4)
print(rand)

[0.07088015 0.95444715 0.91821993 0.54069593]


In [7]:
import numpy as np
rand=np.random.rand(2,3)
print(rand)

[[0.29451856 0.94787195 0.58640245]
 [0.13828334 0.20954036 0.67617196]]


In [8]:
import numpy as np
arr=np.random.randint(0,100,12)
print(arr)

[17 79 51 78 33 24 88 49 99 14 81 59]


In [10]:
import numpy as np 
arr=np.array([1,2,3,4,5,50])
print(arr)
arr2=arr.reshape(3,2)
print(arr2)

[ 1  2  3  4  5 50]
[[ 1  2]
 [ 3  4]
 [ 5 50]]


In [14]:
#The reshape Function in Rusly allows you to change the shape (dimensions) of an array without changing Its data. This can be useful when you want to rearrange the way data is organized in an array, such as converting a 1-dimensional array inte a 2-dimensional matrix or vice versa, or changing the tle of a multi-dimensional array while saintaining the total number of elements.

In [13]:
import numpy as np
arr=np.random.randint(0,100,12)

print(arr)

arr=arr.reshape(4,3)

print(arr)

print("Array values is ",arr[0][1])

print("Array values is ",arr[1][0])

print(arr.shape)

arr=arr.reshape(-1,4)

print(arr)

arr=arr.reshape(2,-1)

print(arr)

[79 78 55 84 86  1  1 85 94 21 54 94]
[[79 78 55]
 [84 86  1]
 [ 1 85 94]
 [21 54 94]]
Array values is  78
Array values is  84
(4, 3)
[[79 78 55 84]
 [86  1  1 85]
 [94 21 54 94]]
[[79 78 55 84 86  1]
 [ 1 85 94 21 54 94]]


In [18]:
import numpy as np
np.random.seed(145)
arr=np.random.randint(0,100,12)
print(arr)

[37 86 87 18 90 69  8 53 33 32 40 26]


In [23]:
import numpy as np
np.random.seed(111)
arr=np.random.randint(1,500,30)
arr=arr.reshape(6,5)
print(arr)

[[341 365 469 213  87]
 [276 170 323 119 467]
 [297 456 442   8 269]
 [267 450 369 217 285]
 [271 419  22  55 201]
 [ 38 461 231 187 269]]


In [24]:
print(arr[2:,2:])

[[442   8 269]
 [369 217 285]
 [ 22  55 201]
 [231 187 269]]


In [25]:
print(arr[3:5,2:4])

[[369 217]
 [ 22  55]]


In [27]:
import numpy as np
arr=np.array([1,20,5,9,3,4,8,5,6,2,25,2,2265,3,33,1])
slicing=arr[4:9]
print("new slicing",slicing)
print("new array",arr)
print(type(slicing))
print(type(arr))
slicing[:]=0
print("old Slicing ",slicing)
print("old array ",arr)

new slicing [3 4 8 5 6]
new array [   1   20    5    9    3    4    8    5    6    2   25    2 2265    3
   33    1]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
old Slicing  [0 0 0 0 0]
old array  [   1   20    5    9    0    0    0    0    0    2   25    2 2265    3
   33    1]


In [28]:
import numpy as np 
arr=np.arange(1,15)
print(arr)
print(arr[arr%2!=0])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1  3  5  7  9 11 13]


In [29]:
import numpy as np

arr=np.arange(1,15)

print(arr)

print(arr[arr%2==0])

print(arr[arr%2!=0])

print(arr[arr>8])

arr [arr%2==0]

print(arr)

arr=np.arange(1,8)

print(arr+2)

print(arr*2)

print(arr**2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  4  6  8 10 12 14]
[ 1  3  5  7  9 11 13]
[ 9 10 11 12 13 14]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14]
[ 1  4  9 16 25 36 49]


In [31]:
import numpy as n

arr=n.array([10,20,30,25,6,21])

print(n.min(arr))

print(n.max(arr))

print(n.argmin(arr))

print(n.argmax(arr))

print(n.sqrt(arr))

print(n.sin(arr))

print(n.cos(arr))

6
30
4
2
[3.16227766 4.47213595 5.47722558 5.         2.44948974 4.58257569]
[-0.54402111  0.91294525 -0.98803162 -0.13235175 -0.2794155   0.83665564]
[-0.83907153  0.40808206  0.15425145  0.99120281  0.96017029 -0.54772926]


In [34]:
import numpy as np

np.random.seed (122)

mat=np.random.randint(1,21,9).reshape(3,3)

print(mat)

print(np.sum (mat))

print (np.cumsum(mat))

print(np.min (mat))

print(np.max(mat))

print("---------")

print(np.sum (mat, axis=0))

print(np.min (mat,axis=0))

print (np.max(mat,axis=0))

print(np.cumsum(mat,axis=0))

[[16 11 13]
 [17 13 16]
 [ 3 16 11]]
116
[ 16  27  40  57  70  86  89 105 116]
3
17
---------
[36 40 40]
[ 3 11 11]
[17 16 16]
[[16 11 13]
 [33 24 29]
 [36 40 40]]


In [35]:
import numpy as np 
np.random.seed(122)
mat=np.random.randint(1,21,10)
print(mat)
np.random.shuffle(mat)
print(mat)
print(np.unique(mat,return_index=True,return_counts=True))
print(np.unique(mat).size)

[16 11 13 17 13 16  3 16 11 10]
[13 16 16 11 16 10 11 13 17  3]
(array([ 3, 10, 11, 13, 16, 17]), array([9, 5, 3, 0, 1, 8], dtype=int64), array([1, 1, 2, 2, 3, 1], dtype=int64))
6


In [1]:
#26/7/2024

In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
indicies=np.where(arr>3)
print(indicies)

(array([3, 4], dtype=int64),)


In [4]:
import numpy as np 
arr=np.array([[1,2,3],[4,5,6]])
transposed_arr=np.transpose(arr)
print(transposed_arr)

[[1 4]
 [2 5]
 [3 6]]


In [5]:
import numpy as np
arr=np.array([1,2,3,4,5])
mean_value=np.mean(arr)
print(mean_value)

3.0


In [6]:
import numpy as np
arr=np.array([1,2,3,4,5])
median=np.median(arr)
print(median)

3.0


In [10]:
import numpy as np
sorted_array=np.array([1,3,5,7,9])
index=np.searchsorted(sorted_array,6)
print("index to insert 6:",index)

index to insert 6: 3


In [11]:
import numpy as np 
arr=np.array([1,2,3,4,5])
extracted_elements=np.extract(arr>3,arr)
print(extracted_elements)

[4 5]


In [1]:
# 29/7/2024

In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
sub_arrays = np.split(arr, 3)
for sub_arr in sub_arrays:
    print(sub_arr)


[1 2]
[3 4]
[5 6]


In [7]:
import numpy as np
arr = np.array([3, 1, 2, 4, 5])
sorted_arr = np.sort(arr)
print("Sorted array (ascending):", sorted_arr)
sorted_arr_desc = np.sort(arr)[::-1]
print("sorted_arr_desc:",sorted_arr_desc)

Sorted array (ascending): [1 2 3 4 5]
sorted_arr_desc: [5 4 3 2 1]
